### ISSUE TITLE
Implement caching for repository meta analysis

### ISSUE THREAD

**Issue by nscuro** [mehab/DTKafkaPOC#125]
The repository meta analyzer does currently not cache responses from external services.

Not caching results means many unnecessary lookups, reduced throughput, and an increased chance of necessary retries (see #124).

The vulnerability analyzer does have basic caching in place.
We could move the [`CacheConfig`](https://github.com/mehab/DTKafkaPOC/blob/main/vulnerability-analyzer/src/main/java/org/acme/cache/CacheConfig.java) class to the `commons` module.

All repository analyzers will then need to have a dedicated `Cache` instance, similar to how it's done for OSS Index and Snyk clients: https://github.com/mehab/DTKafkaPOC/blob/main/vulnerability-analyzer/src/main/java/org/acme/analyzer/OssIndexAnalyzerConfig.java#L21-L35

**Comment by sahibamittal** [comment]
I'll take this up 👍🏼
