### ISSUE TITLE
Implement internal vulnerability analysis

### ISSUE THREAD

**Issue by nscuro** [mehab/DTKafkaPOC#134]
Migrate the internal vulnerability analysis from the API server to the vulnerability-analyzer service.

**Comment by japurva1502** [comment]
I will work on this

**Comment by japurva1502** [comment]
Proposal:
Now that we have read access from Quarkus application to api-server's database, it makes more sense to onboard the internal analyzer on Quarkus app.

As like OSS/Snyk analyzer, Internal analyzer would also listen on the "dtrack.vuln-analysis.component" topic for incoming components from BomUploadProcessingTask and the VulnerabilityResult from the analysis will be sent back on the "dtrack.vuln-analysis.vulnerability" topic back to api-server.
So, we would be plugging internal analyzer in our VulnerabilityAnalyzerTopology.

If the internal analyzer is enabled the components will be forwarded to Internal analyzer.

For analysis, InternalAnalyzer would make a read call to VulnerableSoftware table in the database.
For components with cpe, analyzer would be querying using the combination of cpe(part, vendor, product) and purl
For components without cpe and valid purl, the query will be on purl.

Currently, we do not have caching implemented for recently analyzed components for Internal analyzer, we should implement that as it would be more performant to query cache than database

Currently this proposal doesn't take FuzzySearch(using lucene) into account, will need to search more on this and will update the issue later

**Comment by nscuro** [comment]
FWIW this is done, we can log further improvements in new issues if necessary. Thanks @japurva1502 for implementing! 🚀
