### ISSUE TITLE
Make services "k8s-ready"

### ISSUE THREAD

**Issue by nscuro** [mehab/DTKafkaPOC#138]
For our load testing (#136), we'll need to run the services in a k8s cluster to account for dynamic scaling etc.

In order for that to work, the services need to be deployable using Helm. Quarkus has a Helm extension that may be useful: https://quarkus.io/blog/quarkus-helm/

For verification, all services must be deployable in a local Minikube or KIND cluster.

**Comment by nscuro** [comment]
Note: As the vulnerability analyzer makes use of state stores for batching, a production-ready k8s deployment would need to involve `StatefulSet`s, see https://itnext.io/how-to-use-kubernetes-to-deploy-stateful-kafka-streams-applications-872c77f03c3a

For an initial MVP that may not be necessary, given that state stores *can* be rebuilt from the respective changelog topic.

**Comment by mehab** [comment]
I can take this up

**Comment by mehab** [comment]
Updated application to use native binary version of vulnerability-analyzer in this PR https://github.com/mehab/DTKafkaPOC/pull/198 . Tested this and PR has been merged to main :)
