### ISSUE TITLE
Onboarding of Notification Service on to Kafka

### ISSUE THREAD

**Issue by japurva1502** [mehab/DTKafkaPOC#63]
Proposed changes for Notification Service:

1. Move the Notification module on to Kafka Service.

2. Currently DT calls notification after any operation that it performs, the notification call goes to NotificationUtil and from there the notification is dispatched from overloaded method
**Proposed Changes** - Instead of dispatching notifications, put the notification object on to kafka topic which will be read by Quarkus service and the Notification is dispatched from the Consumer.

3. The Notification.Dispatch call for Exceptions is scattered throughout the project
**Proposed Changes** - Create a common method for creating the Notification object in case of exceptions in NotificationUtil and again put that notification object on kafka topic

4.The NotificationRouter reads the notification rules from persistence manager
**Proposed Changes** - Since Quarkus application does not have access to database currently, therefore on Quarkus application startup, fetch the NotificationRules from DT using REST Call and Store them in the in-memory data structure in Quarkus application for each NotficationLevel( Informational, Warning and ERROR)

5. Few configs are also read from database
**Proposed Changes** - Add those configs in the application property maintained by quarkus application

**Comment by japurva1502** [comment]
For point#4: We are planning to have DT send config to Quarkus on the Kafka topic on startup and when users send any config changes to DT.
Quarkus service will then store the config in Kafka-cache in globalKTable  with log.cleanup.policy=compact so that we store only latest config per key

**Comment by japurva1502** [comment]
https://excalidraw.com/#room=8b5865ebb81bc8c25361,yqLBDX_xlqX6aIGQitGpRA

**Comment by japurva1502** [comment]
Discussed with the Team that we will be integrating Api Server Database with Quarkus application in read-only mode, so wont need to store the configs in kafka cache and we will have only one source of truth

**Comment by syalioune** [comment]
Please check https://github.com/mehab/DTKafkaPOC/issues/69#issuecomment-1298515352 as it is related to this proposal.
With regards to the linked comment, two remarks here :

- Notification Service should be in an independent module IMHO for separation of concerns
- Notification configuration should also be owned by that module (especially updates)

**Comment by japurva1502** [comment]
This is done !
