### ISSUE TITLE
Separate responsibilities in different applications

### ISSUE THREAD

**Issue by nscuro** [mehab/DTKafkaPOC#98]
As there should really only be a single streams topology per application, we currently have shoved different responsibilities into the same topology.

Not only does this bloat the topology diagram, it also messes with scalability. For example, in the current `main` branch, we have both vulnerability analysis and notification sending. With the default `kafka-streams.num.stream.threads=3`, every stream thread gets assigned **20** partitions.

![Screenshot from 2022-11-17 11-46-30](https://user-images.githubusercontent.com/5693141/202430320-53141c0c-e9c4-42a2-ba83-c7fa490c795f.png)

Partitions are evenly divided, because all topics we have as of now have exactly 3 partitions.

If we increase the stream threads to something like 12 however, the whole picture looks more messy:

![Screenshot from 2022-11-17 11-55-00](https://user-images.githubusercontent.com/5693141/202430499-08074d8c-19b2-47c6-81c9-298c916e25f4.png)

3 tasks are assigned 17 partitions, while others only get one. 

Those 3 tasks are involved in both notification sending and vulnerability analysis, which means a high load of notifications can block vulnerability analysis, and a high load on the analysis part can block notifications. Not a good situation to be in.

Let's separate the vulnerability analysis, notification sending, and repo meta analysis into their own applications. We can do this by splitting the Maven project into multiple modules. Each application should have its own topology, and its own consumer group.

**Comment by japurva1502** [comment]
Fixed with PR : https://github.com/mehab/DTKafkaPOC/pull/99
